#!/bin/sh -e

cat > makeinfo <<EOF
#!/bin/sh
printf 'makeinfo (GNU texinfo) 5.2\n'
EOF

chmod +x makeinfo
export PATH=$PATH:$PWD

./configure \
    --prefix=/usr \
    --build=powerpc64le-linux-musl \
    --host=powerpc64le-linux-musl \
    --enable-targets=powerpc64le-linux-musl \
    --disable-multilib \
    --disable-werror \
    --disable-nls \
    --with-mmap \
    --with-system-zlib

make
make DESTDIR="$1" install
