#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

# 'rust' checksums files in 'vendor/', but we patch a few files.
for vendor in libc openssl-sys; do
    sed -i 's/\("files":{\)[^}]*/\1/' "vendor/$vendor/.cargo-checksum.json"
done

sed -i 's/(target.contains("linux-gnu") || target.contains("apple-darwin"))/target.contains("linux-gnu") || target.contains("apple-darwin")/g' src/bootstrap/lib.rs

cat > config.toml <<EOF
[llvm]
link-shared = true

[build]
build               = "powerpc64le-unknown-linux-musl"
host                = [ "powerpc64le-unknown-linux-musl" ]
target              = [ "powerpc64le-unknown-linux-musl" ]
docs                = false
compiler-docs       = false
extended            = true
tools               = ["cargo"]
submodules          = false
python              = "python3"
locked-deps         = true
vendor              = true
sanitizers          = false
profiler            = false
full-bootstrap      = false
rustc               = "$(pwd)/bootstrap/usr/bin/rustc"
cargo               = "$(pwd)/bootstrap/usr/bin/cargo"
cargo-native-static = true
local-rebuild       = true

[install]
prefix = "/usr"

[rust]
channel          = "stable"
rpath            = true
codegen-units    = 1
debuginfo-level  = 0
debug            = false
backtrace        = false
jemalloc         = false
debug-assertions = false
codegen-tests    = false

[target.powerpc64le-unknown-linux-musl]
llvm-config = "/usr/bin/llvm-config"
crt-static  = false
EOF

python3 ./x.py build -j "$(nproc)"
DESTDIR="$1" python3 ./x.py install
